#ifndef DECLARACIONRECUADRO_H_INCLUDED
#define DECLARACIONRECUADRO_H_INCLUDED

/// PARAMETROS: PRIMEROS DOS INT (LUGAR) SEGUNDOS DOS INT(TAMAÑO)
/// LUGAR = PRIMER INT (COLUMNA) SEGUNDO INT (FILA)
/// TAMAÑO = PRIMER INT (ANCHO) SEGUNDO INT (ALTURA)
void dibujarRecuadro(int, int, int, int);

#endif // DECLARACIONRECUADRO_H_INCLUDED
